version: '3.8'

services:
  # 后端开发服务
  backend-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: sehuatang-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # 数据库配置
      - DATABASE_HOST=postgres-dev
      - DATABASE_PORT=5432
      - DATABASE_NAME=sehuatang_dev
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=sehuatang123
      
      # 应用配置
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_RELOAD=true
      - DEBUG=true
      
      # 全局代理配置
      - HTTP_PROXY=http://192.168.31.85:7891
      - HTTPS_PROXY=http://192.168.31.85:7891
      - http_proxy=http://192.168.31.85:7891
      - https_proxy=http://192.168.31.85:7891
      - NO_PROXY=localhost,127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,sehuatang-dev-network
      
    volumes:
      # 代码热更新
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/.venv
      
      # 数据持久化
      - ./data:/app/data
      - ./logs:/app/logs
      
    depends_on:
      - postgres-dev
      
    networks:
      - sehuatang-dev-network

  # 前端开发服务
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend.dev
    container_name: sehuatang-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # 前端代码热更新
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://backend-dev:8000
    depends_on:
      - backend-dev
    networks:
      - sehuatang-dev-network

  # 开发数据库
  postgres-dev:
    image: postgres:15-alpine
    container_name: sehuatang-postgres-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=sehuatang_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sehuatang123
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    ports:
      - "5433:5432"  # 使用不同端口避免冲突
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - sehuatang-dev-network

volumes:
  postgres_dev_data:

networks:
  sehuatang-dev-network:
    driver: bridge
