# docker-compose.prod.yml - 前后端合一生产环境
version: '3.8'

services:
  sehuatang-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: sehuatang-app
    restart: unless-stopped
    ports:
      - "8000:8000"  # 只需要一个端口！
    environment:
      # 数据库配置
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=sehuatang_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=sehuatang123
      
      # 应用配置
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_RELOAD=false
      - DEBUG=false
      
    volumes:
      # 数据持久化
      - ./data:/app/data
      - ./logs:/app/logs
      
    depends_on:
      - postgres
      
    networks:
      - sehuatang-network

  postgres:
    image: postgres:15-alpine
    container_name: sehuatang-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=sehuatang_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sehuatang123
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - sehuatang-network

volumes:
  postgres_data:

networks:
  sehuatang-network:
    driver: bridge
